name: Push
on:
  push:
    branches: [master, main]
    tags: ["*"]
permissions:
  contents: read
jobs:
  check:
    name: Lint
    if: github.ref_type == 'branch'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command just check

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command just setup
      - run: nix develop --command just build
      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: obs-moq-linux-x86_64
          path: build_x86_64/obs-moq.so

  build-macos:
    name: Build (macOS)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command just setup
      - run: nix develop --command just build
      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: obs-moq-macos-arm64
          path: build_macos/RelWithDebInfo/obs-moq.plugin

  build-windows:
    name: Build (Windows)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: choco install just pkgconfiglite ffmpeg-full -y
      - name: Setup
        shell: bash
        run: |
          export PKG_CONFIG_PATH="/c/ProgramData/chocolatey/lib/ffmpeg-full/tools/ffmpeg/lib/pkgconfig"
          just setup
      - name: Build
        shell: bash
        run: just build
      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: obs-moq-windows-x64
          path: build_x64/RelWithDebInfo/obs-moq.dll

  release:
    name: Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: [build-linux, build-macos, build-windows]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: artifacts/**/*
